fix: Properly parse tsconfig.json
getappmap/appmap-node pull request #114
Opened 2024-02-15 19:55 UTC by zermelo-wisen

Fixes #91

tsconfig.json cannot be parsed with JSON.parse properly. It can have trailing comma which is not legal in JSON. Use typescript.readConfigFile instead.

2024-02-29 13:52 UTC, dividedmind requested changes
I'm very wary of pulling in whole typescript — it's quite large and will make the recommended usage with _npx_ particularly more inconvenient. I'd look into other ways of parsing it — [tsconfck](https://www.npmjs.com/package/tsconfck) looks promising.

BTW, any change like this should include test cases that didn't work before and now do.

2024-03-01 07:44 UTC, zermelo-wisen commented
> I'm very wary of pulling in whole typescript — it's quite large and will make the recommended usage with _npx_ particularly more inconvenient. I'd look into other ways of parsing it — [tsconfck](https://www.npmjs.com/package/tsconfck) looks promising.
> 
> BTW, any change like this should include test cases that didn't work before and now do.

I dropped `typescript` and `strip-json-comments` libraries and added `json5` for parsing the `tsconfig.json`.

For the test case, I added a trailing comma to the `tsconfig.json` in `test/typescript-esm`, since tsconfig parsing code path is covered with the `"esm-loader is loaded when required"` integration test in `typescript-esm.test.ts`.

2024-03-01 11:53 UTC, dividedmind approved these changes
Perfect, thank you!

2024-03-01 11:53 UTC, merged

2024-03-01 11:56 UTC, appland-release commented
:tada: This PR is included in version 2.16.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/appmap-node/v/2.16.1)
- [GitHub release](https://github.com/getappmap/appmap-node/releases/tag/v2.16.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: