fix: Don't block with readFileSync in remote recording finish
getappmap/appmap-node pull request #145
Opened 2024-04-22 12:49 UTC by zermelo-wisen

Fixes #70

2024-04-22 13:35 UTC, dividedmind requested changes
Please make sure errors are reported instead of being silently swallowed. Easiest way to do this is probably to spin out an async function instead of using the callback flavor of `readFile`. (Node will show an error message when an exception is thrown in a promise but not caught, which is good enough IMO.)

2024-04-22 13:46 UTC, zermelo-wisen commented
Actually my first attempt was to make the Proxy trap for emit asynchronous and use fs.promisses version of readFile instead. But I "felt" it won't be correct even if I wasn't able to find an evidence.

2024-04-22 13:54 UTC, dividedmind commented
> Actually my first attempt was to make the Proxy trap for emit asynchronous and use fs.promisses version of readFile instead. But I "felt" it won't be correct even if I wasn't able to find an evidence.

Not sure what you mean with proxy trap, but here's roughly what I have in mind:

```typescript
        if (recording.finish()) {
          res.writeHead(200);
          const { path } = recording;
          void (async () => {
            res.end(await readFile(path));
            await rm(path);
            reset();
          })();
        } else {
          res.writeHead(200).end("{}");
          reset();
        }
```

2024-04-23 13:32 UTC, dividedmind approved these changes

2024-07-23 13:07 UTC, merged

2024-07-23 13:10 UTC, appland-release commented
:tada: This PR is included in version 2.23.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/appmap-node/v/2.23.1)
- [GitHub release](https://github.com/getappmap/appmap-node/releases/tag/v2.23.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: