fix: Handle external source maps
getappmap/appmap-node pull request #97
Opened 2024-01-21 10:17 UTC by dividedmind

Fixes #96

2024-01-22 17:37 UTC, dustinbyrne requested changes

2024-01-22 17:37 UTC, dustinbyrne commented on src/transform.ts
> +    process.version < "v18.19" &&
Yes, this does seem worth fixing

2024-01-22 17:39 UTC, dividedmind commented on src/transform.ts
> +    process.version < "v18.19" &&
Good catch, thanks! Fixed.

2024-01-24 10:47 UTC, zermelo-wisen approved these changes

2024-01-24 20:19 UTC, merged

2024-01-24 20:21 UTC, appland-release commented
:tada: This PR is included in version 2.14.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/appmap-node/v/2.14.1)
- [GitHub release](https://github.com/getappmap/appmap-node/releases/tag/v2.14.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: